'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {courseRequest} from './course-client';
import './course.css';
type Offer={id:string;title:string;description:string;sessions:number;minutes:number;amount:number;teacher:string;languages:string[]};
export default function CoursesPage(){
  const [offers,setOffers]=useState<Offer[]>([]),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
  useEffect(()=>{courseRequest<{offers:Offer[]}>('/api/courses').then(r=>{setOffers(r.offers);setLoaded(true);}).catch(e=>setMessage(e.message));},[]);
  async function apply(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{const r=await courseRequest<{message:string}>('/api/courses',{offerId:selected,name:form.get('name'),email:form.get('email'),language:form.get('language'),timezone:form.get('timezone'),goal:form.get('goal'),consent:form.get('consent')==='on'});setMessage(r.message);setSelected('');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function access(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const r=await courseRequest<{message:string}>('/api/courses',{action:'access',email:new FormData(event.currentTarget).get('email')});setMessage(r.message);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <main className="course-page" lang="en"><header><Link href="/">Home</Link><Link href="/learn">Try the free workbook</Link><Link href="/student-area">My courses</Link></header><p>LEARN KOREAN · ONE CONVERSATION AT A TIME</p><h1>Your first real conversations start here.</h1><p className="intro">Start with your name, your favorite coffee, and the places you want to go. Apply for a teacher-led course. We will review your goals and availability before inviting you to pay.</p>
    <div className="course-grid">{offers.map(o=><article className="course-card" key={o.id}><p className="course-status">{o.teacher} · {o.languages.join(' / ')}</p><h2>{o.title}</h2><p>{o.description}</p><p>{o.sessions} lessons × {o.minutes} minutes</p><p><strong>₩{o.amount.toLocaleString()} KRW</strong> · total package price</p><button onClick={()=>{setSelected(o.id);setMessage('');setTimeout(()=>document.getElementById('application')?.scrollIntoView({behavior:'smooth'}),0);}}>Apply for this course</button></article>)}</div>
    {loaded&&!offers.length&&<p className="course-message">New courses are being prepared. You can start with the free workbook today.</p>}
    {selected&&<section className="course-card" id="application"><h2>Tell us about your learning goals</h2><p>{offers.find(o=>o.id===selected)?.title}</p><form className="course-form" onSubmit={apply}><label>Your name<input name="name" required maxLength={100} autoComplete="name"/></label><label>Email<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>Preferred support language<select name="language"><option value="en">English</option><option value="ja">日本語</option><option value="zh">中文</option><option value="vi">Tiếng Việt</option><option value="es">Español</option><option value="ko">한국어</option></select></label><label>Your time zone<input name="timezone" required defaultValue={Intl.DateTimeFormat().resolvedOptions().timeZone} placeholder="Europe/London"/></label><label>What would you like to do in Korean? Include your preferred lesson times.<textarea name="goal" required minLength={5} maxLength={1500}/></label><label className="check"><input name="consent" type="checkbox" required/>I agree to share my name, email, time zone and learning goals with the course team to review and manage this application.</label><p>Submitting is free. Payment is requested only after approval. Unused lessons can be refunded from My courses; an ongoing lesson must be completed first.</p><button disabled={busy}>Send application</button></form></section>}
    <section className="course-card"><h2>Already applied?</h2><p>Request a private sign-in link for your approved course. Use the email you applied with.</p><form className="course-form" onSubmit={access}><label>Email<input name="email" type="email" autoComplete="email" required/></label><button disabled={busy}>Email my access link</button></form></section><p role="status" aria-live="polite" className="course-message">{message||(!loaded?'Loading courses…':'Applications are reviewed by the course team.')}</p>
  </main>;
}
