import Link from 'next/link';
import { FIRST_STEPS, LEARNING_SCENES } from '@hangyeol/content';
import { PrintButton } from './PrintButton';

export const metadata = { title: 'First Steps — Printable Korean Workbook | SAMAT' };

export default function PrintWorkbook() {
  return <main className="learning-site printable-workbook" lang="en"><div className="print-toolbar"><Link href="/learn">← Back to workbook / 교재로</Link><PrintButton /></div><header className="print-cover"><p className="learn-eyebrow">SAMAT / FIRST STEPS</p><h1>A little Korean.<br />A whole new world.</h1><p lang="ko">한국어로 시작하는 나의 이야기</p><img src={LEARNING_SCENES.hero.src} alt={LEARNING_SCENES.hero.alt.en} width={1536} height={1024} /><p>14 illustrated beginner missions · English support · Speaking practice</p><p>Name / 이름: ____________________</p><p>Suggested practice: 10–15 minutes per mission. Repeat at your own pace. Read dialogues with a Korean speaker or tutor. This book contains no audio and is not a fluency certificate.</p><ol>{FIRST_STEPS.map((lesson, i) => <li key={lesson.id}><a href={`#print-${lesson.id}`}>{String(i + 1).padStart(2, '0')} · {lesson.title.en}</a></li>)}</ol></header>
    {FIRST_STEPS.map((lesson, index) => <article className="print-lesson" key={lesson.id} id={`print-${lesson.id}`}><p className="learn-eyebrow">MISSION {index + 1} / {FIRST_STEPS.length} · {lesson.minutes} MIN SUGGESTED</p><h2>{lesson.title.en}</h2><p lang="ko">{lesson.title.ko}</p><p><strong>Today I can:</strong> {lesson.goal.en}</p><img src={LEARNING_SCENES[lesson.scene].src} alt={LEARNING_SCENES[lesson.scene].alt.en} width={1536} height={1024} /><h3>01 · Key words</h3><div className="print-words">{lesson.words.map((word) => <p key={word.ko}><strong lang="ko">{word.ko}</strong> — {word.en}</p>)}</div><h3>02 · Useful phrases</h3>{lesson.phrases.map((phrase) => <p key={phrase.ko}><strong lang="ko">{phrase.ko}</strong><br />{phrase.en}</p>)}<div className="print-pattern"><h4 lang="ko">{lesson.pattern.form}</h4><p>{lesson.pattern.explanation.en}</p><p lang="ko">{lesson.pattern.example}</p></div><h3>03 · Read together. Switch roles.</h3>{lesson.dialogue.map((line, i) => <p key={i}><span>{line.speaker}: </span><strong lang="ko">{line.ko}</strong><br />{line.en}</p>)}<p><strong>Real-life note:</strong> {lesson.culture.en}</p><h3>04 · Try it yourself</h3>{lesson.questions.map((question, i) => <div className="print-question" key={i}><p>{i + 1}. {question.prompt.en}</p>{question.options.map((option, j) => <p key={j}>□ {String.fromCharCode(65 + j)}. <span lang={/[가-힣]/.test(option) ? 'ko' : 'en'}>{option}</span></p>)}</div>)}<h3>05 · Your speaking mission</h3><p>{lesson.mission.en}</p><p>My words / 나의 문장:</p><div className="writing-lines" aria-label="Space to write your own sentences" /><p>□ I tried the mission aloud. □ I will review this again.</p><p className="learn-small">Self-check only. Ask your tutor for pronunciation feedback.</p></article>)}
    <section className="print-answer-key"><h2>Answer key & speaking examples</h2><p>More than one spoken answer can work. These are examples, not scripts you must memorize.</p>{FIRST_STEPS.map((lesson, i) => <div key={lesson.id}><h3>{i + 1}. {lesson.title.en}</h3>{lesson.questions.map((question, j) => <p key={j}>{j + 1}. <strong>{String.fromCharCode(65 + question.answer)}</strong> — {question.explanation.en}</p>)}<p lang="ko">{lesson.sample}</p></div>)}</section><footer className="print-credits">SAMAT First Steps · Edition 1 · September 2026. Original AI-assisted educational illustrations. Korean text is typeset separately from the artwork. Created for introductory practice; formal proficiency assessment is not included.</footer></main>;
}
