'use client';
import Link from 'next/link';
import './coursebook.css';
import {useEffect,useState} from 'react';
type Data={learningMessage?:string|null;unit:{unitNo:number;title:string;goalStatement:string;targetForms:string[];targetVocab:string[]};model:string[];tasks:string[];image:{src:string;alt:{en:string;ko:string}};units:{unitNo:number;title:string}[];answer:string;submitted:boolean};
async function request<T>(url:string,body?:unknown):Promise<T>{const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw new Error(data.error?.message??'Please try again.');return data;}
export default function Coursebook(){const [data,setData]=useState<Data|null>(null),[answer,setAnswer]=useState(''),[spoken,setSpoken]=useState(false),[message,setMessage]=useState('Loading your lesson…'),[busy,setBusy]=useState(false);
  async function load(n?:number){setBusy(true);try{const d=await request<Data>(`/api/note/coursebook${n?`?unit=${n}`:''}`);setData(d);setAnswer(d.answer);setSpoken(false);setMessage(d.submitted?'Your previous practice has been saved.':'');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{void load();},[]);
  async function save(){if(!data)return;setBusy(true);try{await request('/api/note/coursebook',{unitNo:data.unit.unitNo,answer,spoken});setMessage('Saved for your teacher to review. Saving does not change your lesson level.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <main className="note-coursebook"><Link href="/">← Learning notebook</Link><h1>My lesson practice · 나의 수업 교재</h1><p>Review your class, try a new example, and share it with your teacher.</p><p role="status">{message}</p>{data&&<>{data.learningMessage&&<p>{data.learningMessage}</p>}<label>Lesson / 수업 <select disabled={busy} value={data.unit.unitNo} onChange={e=>void load(Number(e.target.value))} style={{maxWidth:'100%',padding:10,font:'inherit'}}>{data.units.map(u=><option key={u.unitNo} value={u.unitNo}>{u.unitNo}. {u.title}</option>)}</select></label><article style={{marginTop:24}}><img src={data.image.src} alt={data.image.alt.en} style={{width:'100%',borderRadius:18,aspectRatio:'3/2',objectFit:'cover'}}/><h2>{data.unit.unitNo}. {data.unit.title}</h2><p>{data.unit.goalStatement}</p><h3>Words / 어휘</h3><p style={{fontSize:'var(--fs-h2)',lineHeight:2}}>{data.unit.targetVocab.join(' · ')}</p><h3>Useful forms / 목표 표현</h3><p>{data.unit.targetForms.join(' / ')}</p><h3>Listen with your teacher / 선생님과 읽기</h3>{data.model.map((line,i)=><p key={i} style={{padding:16,borderLeft:'3px solid var(--ink)',background:'var(--surface)'}}>{line}</p>)}<h3>Your turn / 직접 해 보기</h3><ol>{data.tasks.map((task,i)=><li key={i} style={{marginBottom:12}}>{task}</li>)}</ol><label htmlFor="course-answer">My answer / 나의 답</label><textarea id="course-answer" value={answer} maxLength={5000} onChange={e=>setAnswer(e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',minHeight:180,padding:16,font:'inherit',margin:'12px 0',borderRadius:10}}/><label style={{display:'block',marginBottom:20}}><input type="checkbox" checked={spoken} onChange={e=>setSpoken(e.target.checked)}/> I practised saying my answer. / 소리 내어 연습했어요.</label><button disabled={busy||!spoken||answer.trim().length<3} onClick={save} style={{padding:'12px 20px',font:'inherit'}}>Save for my teacher / 선생님께 공유</button><p>These practice materials are drafts. Your teacher checks your answers and chooses when to move to the next lesson.</p></article></>}</main>;
}
