'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { FIRST_STEPS, LEARNING_SCENES } from '@hangyeol/content';
import { LearningNav, type Language } from './LearningNav';

export function Landing() {
  const [language, setLanguage] = useState<Language>('en');
  const [showMeaning, setShowMeaning] = useState(false);
  useEffect(() => {
    try { if (localStorage.getItem('samat-language') === 'ko') setLanguage('ko'); } catch { /* English remains usable. */ }
  }, []);
  const ko = language === 'ko';
  const t = (en: string, kr: string) => ko ? kr : en;
  return <div className="learning-site" lang={language}>
    <a className="learn-skip" href="#main-content">{t('Skip to content', '본문으로 건너뛰기')}</a><LearningNav language={language} onLanguage={setLanguage} />
    <main id="main-content">
      <section className="learn-container landing-hero"><div className="hero-copy">
        <p className="learn-eyebrow"><span className="status-dot" /> {t('YOUR KOREAN STORY STARTS HERE', '한국어로 시작하는 나의 이야기')}</p>
        <h1>{t('A little Korean.', '한국어 한마디.')}<br /><em>{t('A whole new world.', '새로운 나의 세상.')}</em></h1>
        <p className="hero-description">{t('Order your favorite coffee. Find your way through Seoul. Turn a hello into a friendship. Start with the Korean you’ll actually use.', '좋아하는 커피를 주문하고, 서울의 길을 찾고, 인사로 친구가 되는 경험. 바로 써먹을 수 있는 한국어부터 시작하세요.')}</p>
        <div className="learn-actions"><Link className="learn-button" href="/learn">{t('Begin your first lesson', '첫 미션 시작하기')} <span aria-hidden="true">↗</span></Link><a className="learn-text-link" href="#peek">{t('Take a little peek', '교재 살짝 보기')} <span aria-hidden="true">↓</span></a></div>
        <p className="hero-footnote">{t('Free beginner workbook · No account needed · Go at your pace', '무료 입문 교재 · 가입 없이 체험 · 내 속도에 맞게')}</p>
      </div><div className="hero-art"><img src={LEARNING_SCENES.hero.src} alt={LEARNING_SCENES.hero.alt[language]} width={1536} height={1024} fetchPriority="high" /><div className="hero-note"><span className="learn-eyebrow">YOUR FIRST WORDS</span><strong lang="ko">안녕하세요!</strong><span>Hello, a new beginning.</span><span className="note-spark" aria-hidden="true">✳</span></div><span className="hero-art-caption">SEOUL, ONE CONVERSATION AT A TIME</span></div></section>
      <div className="learn-promise"><div className="learn-container promise-grid"><p><strong>14</strong><span>{t('small, real-life missions', '일상 속 작은 미션')}</span></p><p><strong>10–15</strong><span>{t('minutes of suggested practice', '분의 권장 연습 시간')}</span></p><p><span className="promise-symbol" aria-hidden="true">가 ↔ A</span><span>{t('Korean, with English support', '영어 뜻풀이와 함께')}</span></p><p><span className="promise-symbol" aria-hidden="true">↗</span><span>{t('One useful step at a time', '한 번에 하나씩, 직접 말하기')}</span></p></div></div>
      <section id="journey" className="learn-container learn-section"><div className="section-heading"><div><p className="learn-eyebrow">01 / {t('A LANGUAGE FOR REAL LIFE', '일상에서 쓰는 언어')}</p><h2>{t('Less memorizing.', '외우는 부담은 작게.')}<br /><em>{t('More living.', '말하는 즐거움은 크게.')}</em></h2></div><p>{t('Every lesson takes you somewhere. Learn a few useful words, try a conversation, and make it your own.', '미션마다 새로운 장면을 만나요. 꼭 필요한 단어와 대화를 익히고, 내 이야기로 바꿔 말해 보세요.')}</p></div>
        <div className="scene-card-grid">{[FIRST_STEPS[3]!, FIRST_STEPS[4]!, FIRST_STEPS[6]!].map((lesson, i) => <Link href={`/learn?lesson=${lesson.id}`} className="scene-card" key={lesson.id}><div className="scene-card-image"><img src={LEARNING_SCENES[lesson.scene].src} alt={LEARNING_SCENES[lesson.scene].alt[language]} loading="lazy" width={1536} height={1024} /><span lang="ko">{['한 잔 주세요', '이거 매워요?', '어디예요?'][i]}</span></div><div className="scene-card-meta"><span className="learn-eyebrow">{t('EVERYDAY KOREAN', '생활 한국어')} / 0{i + 1}</span><span aria-hidden="true">↗</span></div><h3>{lesson.title[language]}</h3><p>{lesson.goal[language]}</p></Link>)}</div><Link className="learn-text-link all-lessons" href="/learn">{t('Explore all 14 missions', '14개 미션 모두 보기')} →</Link>
      </section>
      <section id="peek" className="workbook-peek"><div className="learn-container peek-grid"><div className="peek-copy"><p className="learn-eyebrow">02 / {t('YOUR WORKBOOK, REIMAGINED', '직접 해보는 교재')}</p><h2>{t('See it. Say it.', '그림으로 보고.')}<br /><em>{t('Make it yours.', '내 말로 익혀요.')}</em></h2><p>{t('A friendly scene. A sentence you can use today. Just enough explanation to help it click. Then it’s your turn.', '친숙한 장면과 오늘 쓸 수 있는 한 문장. 이해에 꼭 필요한 설명을 읽은 뒤, 직접 말해 볼 차례예요.')}</p><ol className="learning-method"><li><span>01</span>{t('See the situation and learn the key words', '장면을 보고 핵심 단어 익히기')}</li><li><span>02</span>{t('Read together, then switch roles', '대화를 읽고 역할 바꿔 말하기')}</li><li><span>03</span>{t('Try it yourself. Check. Come back tomorrow.', '직접 답하고 확인한 뒤 다음 날 복습하기')}</li></ol><Link href="/learn?lesson=cafe-order" className="learn-text-link">{t('Open this lesson', '이 미션 열기')} →</Link></div>
        <div className="sample-workbook"><div className="sample-workbook-top"><span className="learn-eyebrow">FIRST STEPS / 04</span><span>{t('At the café', '카페에서')}</span></div><img src={LEARNING_SCENES.cafe.src} alt={LEARNING_SCENES.cafe.alt[language]} loading="lazy" width={1536} height={1024} /><div className="sample-workbook-copy"><span className="learn-eyebrow">{t('ONE SENTENCE, MANY POSSIBILITIES', '한 문장으로 여러 가지 주문')}</span><p lang="ko" className="sample-korean">커피 <span>한 잔</span> 주세요.</p><p className="reading-hint" lang="en">keopi han jan juseyo</p><button className="learn-button secondary small" aria-expanded={showMeaning} onClick={() => setShowMeaning(!showMeaning)}>{showMeaning ? t('Hide meaning', '뜻 가리기') : t('Reveal the meaning', '뜻 보기')} ↗</button>{showMeaning && <p className="sample-answer" role="status">One coffee, please. <span lang="ko">한 잔 = one cup · 주세요 = please give me</span></p>}<p className="sample-task">{t('Your turn: swap 커피 for 물. What would you say?', '내 차례: 커피를 물로 바꾸면 어떻게 말할까요?')}</p></div></div>
      </div></section>
      <section className="learn-container learn-section"><div className="section-heading"><div><p className="learn-eyebrow">03 / {t('A SMALL ROUTINE THAT FITS', '내 일상에 맞는 작은 습관')}</p><h2>{t('Your pace.', '나만의 속도.')}<br /><em>{t('Your kind of Korean.', '내게 필요한 한국어.')}</em></h2></div><p>{t('Start with letters or jump into a scene. Keep your progress on this browser, revisit tricky phrases, and take your workbook to a lesson.', '글자부터 시작하거나 필요한 장면을 골라 보세요. 이 브라우저에 진도를 저장하고, 어려운 표현을 복습하고, 수업에도 교재를 가져갈 수 있어요.')}</p></div><div className="path-grid">{[['01', 'Build a foundation', '기초 다지기', 'Letters, greetings, and a first introduction.', '글자, 인사, 첫 자기소개', '01—03'], ['02', 'Step into everyday life', '일상 속으로', 'Order, shop, travel, and talk about your day.', '주문, 쇼핑, 이동, 나의 하루', '04—10'], ['03', 'Tell your own story', '내 이야기 말하기', 'Yesterday, tomorrow, and a whole day in your words.', '어제, 내일, 내 말로 완성하는 하루', '11—14']].map(([n, en, kr, desc, descKo, range]) => <div className="path-card" key={n}><span className="path-number">{n}</span><h3>{t(en!, kr!)}</h3><p>{t(desc!, descKo!)}</p><span className="learn-eyebrow">{t('MISSIONS', '미션')} {range}</span></div>)}</div></section>
      <section id="teachers" className="teacher-invitation"><div className="learn-container teacher-grid"><div><p className="learn-eyebrow">{t('MADE FOR LEARNERS. READY FOR TEACHERS.', '배우는 사람을 위해, 가르치는 사람과 함께')}</p><h2>{t('Bring the conversation', '수업의 중심에')}<br /><em>{t('into your classroom.', '대화를 놓으세요.')}</em></h2><p>{t('Teach with lesson plans, visual slides, role-play prompts, and student review notes. The public workbook is a shared place to begin.', '지도안, 시각 자료, 역할극, 학생 복습 노트까지. 공개 입문 교재를 함께 보며 수업을 시작하세요.')}</p><div className="learn-actions"><Link href="/signup" className="learn-button light">{t('Apply as a teacher', '강사 이용 신청')} ↗</Link><Link href="/login" className="learn-text-link">{t('Teacher login', '강사 로그인')} →</Link></div></div><div className="teacher-checklist"><span className="learn-eyebrow">{t('BEFORE · DURING · AFTER', '수업 전 · 수업 중 · 수업 후')}</span><p><span aria-hidden="true">✓</span>{t('Choose a goal and open your lesson plan', '목표를 정하고 바로 여는 지도안')}</p><p><span aria-hidden="true">✓</span>{t('Show a scene. Let your student speak.', '장면을 보여 주고 학생이 말하는 수업')}</p><p><span aria-hidden="true">✓</span>{t('Leave feedback and plan the next review', '피드백과 다음 복습까지 연결')}</p><small>{t('Teacher accounts require approval. Students access their private notes through a link from their teacher.', '강사 계정은 승인 후 이용합니다. 학생 개인 노트는 선생님이 보낸 링크로 열어요.')}</small></div></div></section>
      <section className="learn-container learn-section faq-section"><div><p className="learn-eyebrow">{t('A FEW THINGS TO KNOW', '시작 전 궁금한 것')}</p><h2>{t('Start with confidence.', '편하게 시작하세요.')}</h2></div><div className="faq-list">{[
        ['Do I need to know any Korean?', '한국어를 전혀 몰라도 되나요?', 'No. Start with the two letter missions, then practice short everyday phrases with English meanings and optional reading hints.', '괜찮아요. 두 개의 한글 미션부터 시작해 영어 뜻풀이와 선택 가능한 읽기 도움말로 짧은 표현을 연습해요.'],
        ['How quickly will I learn?', '얼마나 빨리 배울 수 있나요?', 'Each mission suggests 10–15 minutes of practice. Repeat as often as you need. Completing 14 missions builds a small set of practical skills; it does not guarantee fluency in 14 days.', '미션마다 10~15분 연습을 권장하지만 필요한 만큼 반복하세요. 14개 미션은 실용적인 입문 표현을 익히는 과정이며 14일 유창성을 보장하지 않아요.'],
        ['Is my progress saved?', '진도는 저장되나요?', 'Progress is saved on this browser when storage is available. It is not synced to an account or shared with a teacher. Private lesson notes use the separate teacher invitation flow.', '교재 진도는 저장 공간을 사용할 수 있을 때 이 브라우저에 저장돼요. 계정 간 동기화나 선생님 공유는 하지 않아요. 개인 수업 노트는 별도의 초대 링크로 이용해요.'],
        ['Can I hear the pronunciation?', '발음은 어떻게 배우나요?', 'Read with a Korean tutor or speaker who can model the sounds. This workbook has no recorded audio or automatic pronunciation scoring. Reading hints are approximate.', '한국어 선생님이나 화자와 대화를 읽으며 소리를 익혀요. 이 교재에는 녹음 음원이나 자동 발음 채점이 없어요. 로마자 도움말은 대략적인 읽기 안내예요.'],
      ].map(([en, kr, answer, answerKo]) => <details key={en}><summary>{t(en!, kr!)}<span aria-hidden="true">+</span></summary><p>{t(answer!, answerKo!)}</p></details>)}</div></section>
      <section className="final-invitation"><p className="learn-eyebrow">{t('A SMALL START. A REAL CONVERSATION.', '작은 시작이 진짜 대화로')}</p><h2 lang="ko">우리, 이야기해요.</h2><p>{t('Let’s have a conversation.', '지금, 첫 한국어 미션을 만나 보세요.')}</p><Link href="/learn" className="learn-button">{t('Take your first step', '나의 첫걸음 시작')} ↗</Link></section>
    </main><footer className="learn-container learn-footer"><Link href="/" className="footer-wordmark">samat.</Link><span>{t('A little closer, one word at a time.', '한마디씩, 조금 더 가까이.')}</span><div><Link href="/learn">{t('Workbook', '교재')}</Link><Link href="/licenses">{t('Credits', '출처')}</Link><Link href="/signup">{t('For teachers', '강사 신청')}</Link></div></footer>
  </div>;
}
