/** Isolated PostgreSQL-compatible integration check. Never loads workspace .env files. */
import assert from 'node:assert/strict';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
const manualFixture = new URL('../output/operations-db/manual/package.json', import.meta.url);
const requireFixture = createRequire(existsSync(manualFixture) ? manualFixture : new URL('../output/operations-db/package.json', import.meta.url));
const { PGlite } = requireFixture('@electric-sql/pglite');
const { citext } = requireFixture('@electric-sql/pglite/contrib/citext');
const { PGLiteSocketServer } = requireFixture('@electric-sql/pglite-socket');
const pg = await PGlite.create({ extensions: { citext } });
const port = 15489;
const url = `postgresql://postgres:postgres@127.0.0.1:${port}/postgres?connection_limit=1&connect_timeout=60&pool_timeout=60&sslmode=disable`;
process.env.DATABASE_URL = url;
process.env.DIRECT_URL = url;
process.env.EMAIL_HASH_PEPPER = randomBytes(32).toString('hex');
process.env.EMAIL_ENC_KEY = randomBytes(32).toString('base64');
process.env.MAGIC_LINK_SECRET = randomBytes(32).toString('hex');
process.env.JWT_ACCESS_SECRET = randomBytes(32).toString('hex');
process.env.NOTE_BASE_URL = 'http://127.0.0.1:3218';
process.env.MAIL_ENABLED = 'false';
process.env.PAYMENTS_LIVE_ENABLED = 'false';
process.env.TOSS_CLIENT_KEY = '';
process.env.TOSS_SECRET_KEY = '';
process.env.TOSS_BILLING_CLIENT_KEY = '';
process.env.TOSS_BILLING_SECRET_KEY = '';
for (const file of ['20260902000000_init','20260909000000_operations','20260909010000_tuition']) {
  await pg.exec(await readFile(new URL(`../packages/db/prisma/migrations/${file}/migration.sql`, import.meta.url), 'utf8'));
}
const server = new PGLiteSocketServer({ db: pg, host: '127.0.0.1', port, debug: process.env.PGLITE_DEBUG === '1' });
await server.start();
const core = await import('../packages/core/src/index.js');
const { getPrisma } = await import('../packages/db/src/index.js');
const prisma = getPrisma();
const checks: string[] = [];
try {
  await prisma.$connect();
  const teacher = await prisma.teacher.create({ data: { name:'Fixture Teacher',email:'fixture@example.test',passwordHash:'not-a-login-password',approvalStatus:'approved',rateTier:'B',billingStatus:'ok' } });
  const student = await core.createStudent({ teacherId:teacher.id,name:'Fixture Learner',email:'learner@example.test',l1Code:'en',platform:'direct' });
  await core.verifyStudent(student.id);
  assert.equal((await prisma.student.findUniqueOrThrow({where:{id:student.id}})).status,'active');
  checks.push('Student registration and invitation verification persist in the isolated database.');
  await assert.rejects(()=>core.startLesson({teacherId:teacher.id,studentId:student.id}));
  const placementAnswers: {questionId:string;choiceIndex:number}[]=[];
  let placement=core.replayLevelAnswers(placementAnswers);
  while(!placement.done){placementAnswers.push({questionId:placement.question!.id,choiceIndex:-1});placement=core.replayLevelAnswers(placementAnswers);}
  await core.saveLevelResult(student.id,placement.state);
  const first = await core.startLesson({teacherId:teacher.id,studentId:student.id});
  const duplicate = await core.startLesson({teacherId:teacher.id,studentId:student.id});
  assert.equal(first.lessonId,duplicate.lessonId);
  assert.equal(first.lessonNo,1);
  assert.ok(first.unitId);
  await core.submitReport({teacherId:teacher.id,lessonId:first.lessonId,expressions:['안녕하세요.'],errors:[],outcome:'repeat'});
  await core.submitReport({teacherId:teacher.id,lessonId:first.lessonId,expressions:['안녕하세요.'],errors:[],outcome:'repeat'});
  assert.equal(await prisma.vocabCard.count({where:{studentId:student.id}}),1);
  assert.equal(await prisma.notification.count(),5);
  const plan = await core.teachingPlan(teacher.id,student.id);
  assert.equal(plan.nextLessonNo,1);
  const repeated = await core.startLesson({teacherId:teacher.id,studentId:student.id});
  assert.equal(repeated.lessonNo,1);
  assert.notEqual(repeated.lessonId,first.lessonId);
  assert.equal(repeated.billing.cycleOpened,true);
  await core.submitReport({teacherId:teacher.id,lessonId:repeated.lessonId,expressions:['저는 미나예요.'],errors:[],outcome:'pass'});
  const next = await core.startLesson({teacherId:teacher.id,studentId:student.id});
  assert.equal(next.lessonNo,2);
  checks.push('Repeated unit stays at 1; passing advances to 2; usage billing counts sessions; duplicate start/report is idempotent.');
  const order = await core.createTopupOrder(teacher.id,10000);
  const verified={orderId:order.id,paymentKey:'fixture-payment',totalAmount:10000,currency:'KRW',status:'DONE',balanceAmount:10000};
  await core.reconcilePayment(verified);
  await core.reconcilePayment(verified);
  assert.equal((await prisma.teacher.findUniqueOrThrow({where:{id:teacher.id}})).creditBalance,10000);
  assert.equal(await prisma.creditTopup.count(),1);
  await assert.rejects(()=>core.reconcilePayment({...verified,totalAmount:1}));
  await core.reconcilePayment({...verified,status:'CANCELED',balanceAmount:0});
  await core.reconcilePayment({...verified,status:'CANCELED',balanceAmount:0});
  assert.equal((await prisma.teacher.findUniqueOrThrow({where:{id:teacher.id}})).creditBalance,0);
  checks.push('Verified test payment grants once; tampered amount fails; verified cancellation reverses once. No provider call made.');
  const invoice = await prisma.invoice.create({data:{teacherId:teacher.id,billingMonth:new Date('2026-09-01'),totalAmount:10000,chargeAmount:10000,status:'pending'}});
  await assert.rejects(()=>core.handlePgWebhook({invoiceId:String(invoice.id),pgTid:'fixture-invoice',amount:1,status:'paid'}));
  await core.handlePgWebhook({invoiceId:String(invoice.id),pgTid:'fixture-invoice',amount:10000,status:'paid'});
  await core.handlePgWebhook({invoiceId:String(invoice.id),pgTid:'old-failure',status:'failed'});
  assert.equal((await prisma.invoice.findUniqueOrThrow({where:{id:invoice.id}})).status,'paid');
  checks.push('Invoice amount validation and terminal payment state are enforced against persisted data.');
  const { FIRST_STEPS } = await import('../packages/content/src/index.js');
  const token = await core.signStudentSession({studentId:String(student.id),teacherId:String(teacher.id)});
  const { POST, GET } = await import('../apps/teacher/app/api/note/workbook/route.js');
  const lesson=FIRST_STEPS[0]!;
  const response=await POST(new Request('http://127.0.0.1/api/note/workbook',{method:'POST',headers:{cookie:`hg_note=${token}`},body:JSON.stringify({lessonId:lesson.id,note:'My first sentence',complete:true,answers:lesson.questions.map(q=>q.answer),spoken:true})}));
  assert.equal(response.status,200);
  const loaded=await GET(new Request('http://127.0.0.1/api/note/workbook',{headers:{cookie:`hg_note=${token}`}}));
  assert.deepEqual((await loaded.json()).completed,[lesson.id]);
  checks.push('Authenticated workbook completion and writing survive a new API request.');
  assert.deepEqual(await core.runNotifications(),{skipped:'mail-not-enabled'});
  assert.deepEqual(await core.runPaymentCollection(),{skipped:'payment-not-configured'});
  checks.push('Unconfigured mail and payment workers make no outbound call.');
  const offer=await core.saveOffer({teacherId:String(teacher.id),title:'Fixture Korean course',description:'Three private Korean practice lessons for the isolated test.',sessions:3,minutes:50,amount:10001,feeBps:1500,published:true},teacher.id);
  await core.applyForCourse({offerId:offer.id,name:'Course learner',email:'course@example.test',language:'en',timezone:'Asia/Seoul',goal:'Practise conversation in the morning.',consent:true});
  await core.applyForCourse({offerId:offer.id,name:'Duplicate request',email:'COURSE@example.test',language:'en',timezone:'Asia/Seoul',goal:'Practise conversation in the morning.',consent:true});
  assert.equal(await prisma.courseApplication.count(),1);
  const application=await prisma.courseApplication.findFirstOrThrow();
  await core.decideApplication(application.id,'approved',teacher.id);
  await core.decideApplication(application.id,'approved',teacher.id);
  const enrollment=await prisma.tuitionEnrollment.findFirstOrThrow();
  assert.equal(await prisma.tuitionEnrollment.count(),1);
  await core.verifyStudent(enrollment.studentId);
  await assert.rejects(()=>core.startLesson({teacherId:teacher.id,studentId:enrollment.studentId}));
  await assert.rejects(()=>core.ownTuitionOrder(student.id,enrollment.orderId));
  const tuitionPayment={orderId:enrollment.orderId,paymentKey:'fixture-tuition',totalAmount:10001,currency:'KRW',status:'DONE',balanceAmount:10001};
  await core.reconcilePayment(tuitionPayment);await core.reconcilePayment(tuitionPayment);
  const { LEVEL_QUESTIONS } = await import('@hangyeol/content');
  const advancedAnswers: {questionId:string;choiceIndex:number}[]=[];
  let advanced=core.replayLevelAnswers(advancedAnswers);
  while(!advanced.done){const q=LEVEL_QUESTIONS.find(q=>q.id===advanced.question!.id)!;advancedAnswers.push({questionId:q.id,choiceIndex:q.answerIndex});advanced=core.replayLevelAnswers(advancedAnswers);}
  const assigned=await core.saveLevelResult(enrollment.studentId,advanced.state);
  assert.equal(assigned.startUnitNo,211);
  assert.equal((await prisma.student.findUniqueOrThrow({where:{id:enrollment.studentId}})).currentLessonNo,0);
  assert.equal((await core.teachingPlan(teacher.id,enrollment.studentId)).nextLessonNo,211);
  const classOne=await core.startLesson({teacherId:teacher.id,studentId:enrollment.studentId});
  assert.equal(classOne.lessonNo,211);
  await core.saveLevelResult(enrollment.studentId,placement.state);
  assert.equal((await prisma.student.findUniqueOrThrow({where:{id:enrollment.studentId}})).currentLessonNo,211);
  await core.startLesson({teacherId:teacher.id,studentId:enrollment.studentId});
  assert.equal((await prisma.tuitionEnrollment.findUniqueOrThrow({where:{id:enrollment.id}})).used,1);
  await assert.rejects(()=>core.createPayout(teacher.id,teacher.id));
  await core.submitReport({teacherId:teacher.id,lessonId:classOne.lessonId,expressions:['안녕하세요.'],errors:[],outcome:'pass'});
  await core.submitReport({teacherId:teacher.id,lessonId:classOne.lessonId,expressions:['안녕하세요.'],errors:[],outcome:'pass'});
  const payout=await core.createPayout(teacher.id,teacher.id);
  assert.equal(payout.amount,2834);
  await assert.rejects(()=>core.createPayout(teacher.id,teacher.id));
  await core.recordPayout(payout.id,'FIXTURE-NOT-A-REAL-TRANSFER',teacher.id);
  await core.recordPayout(payout.id,'FIXTURE-NOT-A-REAL-TRANSFER',teacher.id);
  const originalFetch=globalThis.fetch;let providerCalls=0;
  process.env.TOSS_CLIENT_KEY='test_gck_fixture';process.env.TOSS_SECRET_KEY='test_gsk_fixture';
  globalThis.fetch=async(input,init)=>{
    assert.ok(String(input).startsWith('https://api.tosspayments.com/v1/payments/fixture-tuition'));
    providerCalls++;
    if(init?.method==='POST'){
      assert.equal(JSON.parse(String(init.body)).cancelAmount,6668);
      assert.ok((init.headers as Record<string,string>)['Idempotency-Key']);
      return Response.json({...tuitionPayment,status:'PARTIAL_CANCELED',balanceAmount:3333});
    }
    return Response.json(tuitionPayment);
  };
  try{await core.refundTuition(enrollment.studentId,enrollment.orderId);await core.refundTuition(enrollment.studentId,enrollment.orderId);assert.equal(providerCalls,2);}
  finally{globalThis.fetch=originalFetch;process.env.TOSS_CLIENT_KEY='';process.env.TOSS_SECRET_KEY='';}
  assert.equal((await prisma.tuitionEnrollment.findUniqueOrThrow({where:{id:enrollment.id}})).refundAmount,6668);
  await assert.rejects(()=>core.startLesson({teacherId:teacher.id,studentId:enrollment.studentId}));
  checks.push('Course application and approval deduplicate; unpaid and foreign student access fail; lesson usage and payouts settle once; verified unused-session cancellation closes remaining lessons. No real payment or bank transfer.');
  const courseToken=await core.signStudentSession({studentId:String(enrollment.studentId),teacherId:String(teacher.id)});
  const coursebook=await import('../apps/teacher/app/api/note/coursebook/route.js');
  const courseResponse=await coursebook.GET(new Request('http://127.0.0.1/api/note/coursebook?unit=1',{headers:{cookie:`hg_note=${courseToken}`}}));
  assert.equal(courseResponse.status,200);
  const lockedUnit=await coursebook.GET(new Request('http://127.0.0.1/api/note/coursebook?unit=250',{headers:{cookie:`hg_note=${courseToken}`}}));
  assert.equal(lockedUnit.status,404);
  const submitted=await coursebook.POST(new Request('http://127.0.0.1/api/note/coursebook',{method:'POST',headers:{cookie:`hg_note=${courseToken}`},body:JSON.stringify({unitNo:1,answer:'안녕하세요. 저는 미나예요.',spoken:true})}));
  assert.equal(submitted.status,200);
  assert.equal((await prisma.learningProgress.findUniqueOrThrow({where:{studentId:enrollment.studentId}})).notes['unit-1'],'안녕하세요. 저는 미나예요.');
  checks.push('Students can read and save their taught unit, while an unstarted unit returns 404.');
  const adaptiveStudent=await core.createStudent({teacherId:teacher.id,name:'Adaptive Learner',email:'adaptive@example.test',l1Code:'en',platform:'direct'});
  await core.verifyStudent(adaptiveStudent.id);await core.saveLevelResult(adaptiveStudent.id,advanced.state);
  const initial=await core.startLesson({teacherId:teacher.id,studentId:adaptiveStudent.id});assert.equal(initial.lessonNo,211);
  const overviewBefore=await core.adaptiveOverview(teacher.id,adaptiveStudent.id);assert.equal(overviewBefore.canAdjust,false);
  await core.submitReport({teacherId:teacher.id,lessonId:initial.lessonId,expressions:['어제 공부했어요.'],errors:[],outcome:'repeat'});
  const overview=await core.adaptiveOverview(teacher.id,adaptiveStudent.id);
  const adjustmentInput={action:'apply',observations:{reading:2,listening:2,speaking:0},reason:'Past tense needs teacher prompts.',mode:'supplement',targetUnitNo:12,anchorLessonId:overview.anchorLessonId,revision:overview.revision,requestId:crypto.randomUUID()};
  await assert.rejects(()=>core.adjustLearning(teacher.id+1000n,adaptiveStudent.id,adjustmentInput));
  await assert.rejects(()=>core.adjustLearning(teacher.id,adaptiveStudent.id,{...adjustmentInput,targetUnitNo:250}));
  await core.adjustLearning(teacher.id,adaptiveStudent.id,adjustmentInput);
  await core.adjustLearning(teacher.id,adaptiveStudent.id,adjustmentInput);
  assert.equal(await prisma.studentActivity.count({where:{studentId:adaptiveStudent.id,kind:'learning_adjustment'}}),1);
  await assert.rejects(()=>core.adjustLearning(teacher.id,adaptiveStudent.id,{...adjustmentInput,requestId:crypto.randomUUID()}));
  assert.equal((await core.teachingPlan(teacher.id,adaptiveStudent.id)).nextLessonNo,12);
  const adaptiveToken=await core.signStudentSession({studentId:String(adaptiveStudent.id),teacherId:String(teacher.id)});
  const adaptiveBook=()=>coursebook.GET(new Request('http://127.0.0.1/api/note/coursebook',{headers:{cookie:`hg_note=${adaptiveToken}`}}));
  assert.equal((await(await adaptiveBook()).json()).unit.unitNo,12);
  const supplement=await core.startLesson({teacherId:teacher.id,studentId:adaptiveStudent.id});assert.equal(supplement.lessonNo,12);
  const oldBook=await coursebook.GET(new Request('http://127.0.0.1/api/note/coursebook?unit=211',{headers:{cookie:`hg_note=${adaptiveToken}`}}));assert.equal(oldBook.status,200);
  await assert.rejects(()=>core.submitReport({teacherId:teacher.id,lessonId:supplement.lessonId,expressions:['연습해요.'],errors:[],outcome:'pass'}));
  await core.submitReport({teacherId:teacher.id,lessonId:supplement.lessonId,expressions:['연습해요.'],errors:[],outcome:'repeat'});
  assert.equal((await core.teachingPlan(teacher.id,adaptiveStudent.id)).nextLessonNo,12);
  const retry=await core.startLesson({teacherId:teacher.id,studentId:adaptiveStudent.id});assert.equal(retry.lessonNo,12);
  await core.submitReport({teacherId:teacher.id,lessonId:retry.lessonId,expressions:['어제 연습했어요.'],errors:[],outcome:'pass',independentPerformance:true});
  assert.equal((await core.teachingPlan(teacher.id,adaptiveStudent.id)).nextLessonNo,211);
  assert.equal((await(await adaptiveBook()).json()).unit.unitNo,211);
  const keepView=await core.adaptiveOverview(teacher.id,adaptiveStudent.id);
  await core.adjustLearning(teacher.id,adaptiveStudent.id,{...adjustmentInput,mode:'keep',targetUnitNo:12,anchorLessonId:keepView.anchorLessonId,revision:keepView.revision,requestId:crypto.randomUUID()});
  assert.equal((await core.teachingPlan(teacher.id,adaptiveStudent.id)).nextLessonNo,211);
  const resumed=await core.startLesson({teacherId:teacher.id,studentId:adaptiveStudent.id});assert.equal(resumed.lessonNo,211);
  await core.submitReport({teacherId:teacher.id,lessonId:resumed.lessonId,expressions:['말해요.'],errors:[],outcome:'repeat'});
  const refreshed=await core.adaptiveOverview(teacher.id,adaptiveStudent.id);
  await core.adjustLearning(teacher.id,adaptiveStudent.id,{...adjustmentInput,mode:'reassign',targetUnitNo:31,observations:{reading:0,listening:0,speaking:0},anchorLessonId:refreshed.anchorLessonId,revision:refreshed.revision,requestId:crypto.randomUUID()});
  const reassigned=await core.startLesson({teacherId:teacher.id,studentId:adaptiveStudent.id});assert.equal(reassigned.lessonNo,31);
  await core.submitReport({teacherId:teacher.id,lessonId:reassigned.lessonId,expressions:['다시 연습해요.'],errors:[],outcome:'pass'});
  assert.equal((await core.teachingPlan(teacher.id,adaptiveStudent.id)).nextLessonNo,32);
  assert.equal(await prisma.lesson.count({where:{studentId:adaptiveStudent.id}}),5);
  assert.equal((await prisma.levelTest.findFirstOrThrow({where:{studentId:adaptiveStudent.id}})).levelCode,'topik6');
  checks.push('Teacher observations schedule a supplement; stale and foreign-owner edits fail; retries save once. Repeat retains supplement, independent pass resumes unit 211, reassignment continues at 32; all five actual sessions and diagnostic history remain. Student workbook follows the plan and retains past units.');
  const auditStudent=await core.createStudent({teacherId:teacher.id,name:'Audit only fixture',email:'audit-only@example.test',l1Code:'en',platform:'direct'});
  await prisma.student.update({where:{id:auditStudent.id},data:{currentLessonNo:1,status:'active'}});
  await prisma.lesson.createMany({data:[1,2,3,4].map(n=>({teacherId:teacher.id,studentId:auditStudent.id,lessonNo:1,startedAt:new Date(`2025-01-0${n}T10:00:00Z`)}))});
  await prisma.studentActivity.createMany({data:['learning_adjustment','learning_performance'].map(kind=>({studentId:auditStudent.id,kind,occurredAt:new Date('2025-01-16T10:00:00Z')}))});
  const auditCycle=await prisma.billingCycle.create({data:{studentId:auditStudent.id,teacherId:teacher.id,cycleNo:1,periodStart:new Date('2025-01-01T00:00:00Z'),periodEnd:new Date('2025-01-29T00:00:00Z'),tier:'B',baseAmount:10000,amount:10000}});
  assert.equal((await core.noteHome(auditStudent.id,new Date('2025-01-16T12:00:00Z'))).streakDays,0);
  await core.runCycleClose(new Date('2025-01-30T00:00:00Z'));
  const closedAudit=await prisma.billingCycle.findUniqueOrThrow({where:{id:auditCycle.id}});
  assert.equal(closedAudit.activityCount,0);assert.equal(closedAudit.lessonCount,4);assert.equal(closedAudit.status,'waived_dormant');
  checks.push('Teacher-only adjustment and performance events do not count as student study or billable activity. Four actual sessions remain outside the introductory grace period even after reassignment to unit 1.');
  await mkdir(new URL('../output/design-review/',import.meta.url),{recursive:true});
  await writeFile(new URL('../output/design-review/operations-db-results.json',import.meta.url),JSON.stringify({checkedAt:new Date().toISOString(),engine:'Isolated in-memory PGlite via PostgreSQL wire protocol; not a production concurrency benchmark',checks},null,2));
  console.log(`PASS: ${checks.length} database integration checks. No real student, account, email, or card used.`);
} finally { await prisma.$disconnect();await server.stop();await pg.close(); }
