'use client';
import {useEffect,useState} from 'react';
import {Shell} from '../../Shell';
import {get,post} from '../../api-client';
import '../../courses/course.css';
type Offer={id:string;teacherId:string;title:string;sessions:number;amount:number;feeBps:number;published:boolean};
type Application={id:string;offerId:string;name:string;language:string;timezone:string;goal:string;status:string};
type Enrollment={id:string;studentId:string;orderId:string;teacherId:string;amount:number;sessions:number;used:number;status:string;refundAmount:number};
type Payout={id:string;teacherId:string;amount:number;status:string;transferReference:string|null};
type Data={offers:Offer[];applications:Application[];enrollments:Enrollment[];payouts:Payout[];teachers:{id:string;name:string}[]};
export default function CourseAdmin(){
  const [data,setData]=useState<Data|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[record,setRecord]=useState<Payout|null>(null);
  async function reload(){setData(await get<Data>('/api/admin/courses'));}
  useEffect(()=>{reload().catch(e=>setMessage(e.message));},[]);
  async function act(body:unknown){setBusy(true);try{await post('/api/admin/courses',body);await reload();setMessage('저장했습니다.');return true;}catch(e){setMessage((e as Error).message);return false;}finally{setBusy(false);}}
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await act({action:'offer',teacherId:f.get('teacherId'),title:f.get('title'),description:f.get('description'),sessions:Number(f.get('sessions')),minutes:Number(f.get('minutes')),amount:Number(f.get('amount')),feeBps:Math.round(Number(f.get('fee'))*100),published:false});}
  const teacher=(id:string)=>data?.teachers.find(t=>t.id===id)?.name??id;
  return <Shell><main className="course-page"><h1>수강·정산 관리</h1><p>가격과 수수료는 승인 시 생성되는 주문에 고정됩니다. 학생에게 보이는 제목·설명은 학생이 이해할 언어로 작성하세요.</p><p role="status" className="course-message">{message||(!data?'불러오는 중입니다.':'최근 신청·수강권·정산 내역을 각각 최대 200건 표시합니다.')}</p>
    <section className="course-card"><h2>수강 과정 등록</h2><form className="course-form" onSubmit={create}><label>담당 강사<select name="teacherId" required><option value="">선택</option>{data?.teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>과정 이름<input name="title" minLength={3} maxLength={90} required/></label><label>학습 목표·수업 방식·예약 및 취소 안내<textarea name="description" minLength={20} maxLength={3000} required/></label><label>수업 횟수<input name="sessions" type="number" min={1} max={100} required/></label><label>회당 수업 시간(분)<input name="minutes" type="number" min={15} max={180} defaultValue={50} required/></label><label>학생 총 결제액(원)<input name="amount" type="number" min={1000} max={5000000} step={1} required/></label><label>플랫폼 수수료율(%)<input name="fee" type="number" min={0} max={100} step={.01} required/></label><button disabled={busy}>비공개 과정으로 저장</button></form></section>
    <section><h2>모집 과정</h2><div className="course-grid">{data?.offers.map(o=><article key={o.id} className="course-card"><h3>{o.title}</h3><p>{teacher(o.teacherId)} · {o.sessions}회 · {o.amount.toLocaleString()}원 · 수수료 {o.feeBps/100}%</p><p>{o.published?'모집 중':'비공개'}</p><button disabled={busy} onClick={()=>act({action:'publish',id:o.id,published:!o.published})}>{o.published?'모집 중지':'모집 시작'}</button></article>)}</div></section>
    <section><h2>수강 신청</h2><p>학습 목표와 가능한 시간을 학생·강사와 확인한 뒤 승인하세요. 승인하면 주문과 수강권이 생성되고 학생 이메일 안내가 발송 대기열에 들어갑니다.</p><div className="course-grid">{data?.applications.map(a=><article key={a.id} className="course-card"><h3>{a.name}</h3><p>{data.offers.find(o=>o.id===a.offerId)?.title}</p><p>{a.language} · {a.timezone}</p><p>{a.goal}</p><p>{a.status}</p>{a.status==='pending'&&<div className="course-actions"><button disabled={busy} onClick={()=>act({action:'decide',id:a.id,decision:'approved'})}>승인 및 주문 생성</button><button disabled={busy} onClick={()=>act({action:'decide',id:a.id,decision:'rejected'})}>거절</button></div>}</article>)}</div></section>
    <section className="course-card"><h2>학생 수강권</h2><div className="course-scroll"><table className="course-table"><thead><tr><th>학생 ID</th><th>담당</th><th>사용/총 회차</th><th>상태</th><th>환불액</th></tr></thead><tbody>{data?.enrollments.map(e=><tr key={e.id}><td>{e.studentId}</td><td>{teacher(e.teacherId)}</td><td>{e.used}/{e.sessions}</td><td>{e.status}</td><td>{e.refundAmount.toLocaleString()}원</td></tr>)}</tbody></table></div></section>
    <section className="course-card"><h2>정산 대기 생성</h2><p>완료 리포트가 있는 수업의 수수료 차감 후 금액을 묶습니다. 송금은 별도로 은행에서 진행하고, 실제 송금 내역을 확인한 뒤 아래에 기록하세요.</p><form className="course-form" onSubmit={e=>{e.preventDefault();void act({action:'payout',teacherId:new FormData(e.currentTarget).get('teacherId')});}}><label>강사<select name="teacherId" required><option value="">선택</option>{data?.teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button disabled={busy}>미정산 완료 수업 묶기</button></form></section>
    <div className="course-grid">{data?.payouts.map(p=><article key={p.id} className="course-card"><h3>{teacher(p.teacherId)} · {p.amount.toLocaleString()}원</h3><p>{p.status==='paid'?'송금 확인 기록 완료':'송금 대기'}</p><p>{p.transferReference}</p>{p.status==='pending'&&<button onClick={()=>setRecord(p)}>실제 송금 내역 기록</button>}</article>)}</div>
    {record&&<section className="course-card"><h2>송금 확인: {teacher(record.teacherId)} · {record.amount.toLocaleString()}원</h2><form className="course-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await act({action:'paid',id:record.id,reference:f.get('reference'),transferred:f.get('transferred')==='on'}))setRecord(null);}}><label>은행 송금 고유 식별자<input name="reference" minLength={6} maxLength={200} required/></label><label className="check"><input name="transferred" type="checkbox" required/>수취인과 금액이 일치하는 실제 송금 완료 내역을 확인했습니다.</label><div className="course-actions"><button disabled={busy}>송금 확인 기록 저장</button><button type="button" onClick={()=>setRecord(null)}>닫기</button></div></form></section>}
  </main></Shell>;
}
